"""
JAX-compatible interpolator using ESMF regridding weights.

This module provides a JAX-friendly interface to apply pre-computed
ESMF regridding weights from netCDF files generated by ESMF_regridweightgen.
"""

import jax
import jax.numpy as jnp
from jax import jit
import numpy as np
import xarray as xr
from typing import Optional, Tuple, Dict, Any
from dataclasses import dataclass
from functools import partial


@dataclass
class ESMFWeights:
    """
    Container for ESMF sparse regridding weights.
    
    ESMF stores weights as a sparse matrix in COO (coordinate) format.
    We store these in a JAX-friendly format for efficient computation.
    """
    # Sparse matrix data (COO format)
    row_indices: jnp.ndarray  # Target grid indices
    col_indices: jnp.ndarray  # Source grid indices
    weights: jnp.ndarray      # Interpolation weights
    
    # Grid dimensions
    src_shape: Tuple[int, ...]
    dst_shape: Tuple[int, ...]
    
    # Optional mask information
    src_mask: Optional[jnp.ndarray] = None
    dst_mask: Optional[jnp.ndarray] = None
    
    # Metadata
    method: str = "unknown"
    src_grid_dims: Optional[Tuple[str, ...]] = None
    dst_grid_dims: Optional[Tuple[str, ...]] = None
    
    @property
    def n_weights(self) -> int:
        """Number of non-zero weights."""
        return len(self.weights)
    
    @property
    def src_size(self) -> int:
        """Total size of source grid."""
        return int(np.prod(self.src_shape))
    
    @property
    def dst_size(self) -> int:
        """Total size of destination grid."""
        return int(np.prod(self.dst_shape))


class ESMFRegridder:
    """
    JAX-compatible regridder using ESMF weights.
    
    This class reads ESMF weight files and provides JIT-compiled
    interpolation functions that work seamlessly in JAX programs.
    """
    
    def __init__(self, 
        weight_file: str,
        src_shape: Tuple[int, ...], 
        dst_shape: Tuple[int, ...],
    ):
        """
        Initialize regridder from ESMF weight file.
        
        Parameters
        ----------
        weight_file : str
            Path to netCDF file generated by ESMF_regridweightgen
        src_shape : tuple of int
            Shape of source grid (e.g., (nlat, nlon))
        dst_shape : tuple of int
            Shape of destination grid (e.g., (nlat, nlon))
        """
        self.weight_file = weight_file
        self.src_shape = src_shape
        self.dst_shape = dst_shape
        
        # Load weights
        self.weights = self._load_weights()
        
        # Create JIT-compiled interpolation function
        self._interp_fn = jit(self._interpolate_impl)
    
    def _load_weights(self) -> ESMFWeights:
        """
        Load ESMF weights from netCDF file using xarray.
        
        ESMF weight files contain:
        - S: sparse weight matrix values
        - col: source (column) indices (1-based in file)
        - row: destination (row) indices (1-based in file)
        """
        # Open dataset with xarray
        ds = xr.open_dataset(self.weight_file)
        
        try:
            # Read sparse matrix data
            # ESMF uses 1-based indexing, convert to 0-based
            col_indices = ds['col'].values - 1
            row_indices = ds['row'].values - 1
            weights = ds['S'].values
            
            # Read metadata if available
            method = ds.attrs.get('map_method', 'unknown')
            
            # Read grid sizes to validate
            src_grid_size = ds.dims['n_a']
            dst_grid_size = ds.dims['n_b']
            
            # Validate dimensions
            expected_src_size = int(np.prod(self.src_shape))
            expected_dst_size = int(np.prod(self.dst_shape))
            
            if src_grid_size != expected_src_size:
                raise ValueError(
                    f"Source grid size mismatch: file has {src_grid_size}, "
                    f"expected {expected_src_size} from shape {self.src_shape}"
                )
            
            if dst_grid_size != expected_dst_size:
                raise ValueError(
                    f"Destination grid size mismatch: file has {dst_grid_size}, "
                    f"expected {expected_dst_size} from shape {self.dst_shape}"
                )
            
            # Read masks if available
            src_mask = None
            dst_mask = None
            
            if 'mask_a' in ds.variables:
                src_mask_flat = ds['mask_a'].values
                src_mask = jnp.array(src_mask_flat).reshape(self.src_shape)
            
            if 'mask_b' in ds.variables:
                dst_mask_flat = ds['mask_b'].values
                dst_mask = jnp.array(dst_mask_flat).reshape(self.dst_shape)
            
            # Try to extract grid dimension names if available
            src_grid_dims = None
            dst_grid_dims = None
            
            if 'src_grid_dims' in ds.attrs:
                src_grid_dims = tuple(ds.attrs['src_grid_dims'].split(','))
            if 'dst_grid_dims' in ds.attrs:
                dst_grid_dims = tuple(ds.attrs['dst_grid_dims'].split(','))
        
        finally:
            ds.close()
        
        # Convert to JAX arrays
        return ESMFWeights(
            row_indices=jnp.array(row_indices, dtype=jnp.int32),
            col_indices=jnp.array(col_indices, dtype=jnp.int32),
            weights=jnp.array(weights, dtype=jnp.float32),
            src_shape=self.src_shape,
            dst_shape=self.dst_shape,
            src_mask=src_mask,
            dst_mask=dst_mask,
            method=method,
            src_grid_dims=src_grid_dims,
            dst_grid_dims=dst_grid_dims
        )
    
    @partial(jit, static_argnums=(0,))
    def _interpolate_impl(self, src_data: jnp.ndarray) -> jnp.ndarray:
        """
        Core interpolation implementation (JIT-compiled).
        
        Applies sparse matrix multiplication: dst = W @ src
        where W is the sparse weight matrix.
        """
        # Flatten source data
        src_flat = src_data.reshape(-1)
        
        # Apply sparse matrix multiplication using scatter-add
        # This is equivalent to: dst[row] += weight * src[col]
        dst_flat = jnp.zeros(self.weights.dst_size, dtype=src_data.dtype)
        
        # Gather source values and multiply by weights
        src_values = src_flat[self.weights.col_indices]
        weighted_values = src_values * self.weights.weights
        
        # Scatter-add to destination
        dst_flat = dst_flat.at[self.weights.row_indices].add(weighted_values)
        
        # Reshape to destination grid
        return dst_flat.reshape(self.weights.dst_shape)
    
    def __call__(self, src_data: jnp.ndarray) -> jnp.ndarray:
        """
        Interpolate data from source grid to destination grid.
        
        Parameters
        ----------
        src_data : jnp.ndarray
            Data on source grid with shape matching src_shape
            
        Returns
        -------
        jnp.ndarray
            Interpolated data on destination grid
        """
        # Validate input shape
        #if src_data.shape != self.src_shape:
        #    raise ValueError(
        #        f"Input shape {src_data.shape} does not match "
        #        f"expected source shape {self.src_shape}"
        #    )
        
        return self._interp_fn(src_data)
    
    def apply_batched(self, src_data: jnp.ndarray, 
                      batch_dims: int = 1) -> jnp.ndarray:
        """
        Apply interpolation to batched data.
        
        Parameters
        ----------
        src_data : jnp.ndarray
            Data with leading batch dimensions followed by grid shape
            e.g., (time, level, lat, lon) or (batch, lat, lon)
        batch_dims : int
            Number of leading batch dimensions
            
        Returns
        -------
        jnp.ndarray
            Interpolated data with same batch dimensions
        """
        # Validate shape
        expected_shape = src_data.shape[:batch_dims] + self.src_shape
        if src_data.shape != expected_shape:
            raise ValueError(
                f"Input shape {src_data.shape} incompatible with "
                f"batch_dims={batch_dims} and src_shape={self.src_shape}"
            )
        
        # Vectorize over batch dimensions
        vectorized_interp = self._interp_fn
        for _ in range(batch_dims):
            vectorized_interp = jax.vmap(vectorized_interp)
        
        return vectorized_interp(src_data)
    
    def regrid_xarray(self, da: xr.DataArray, 
                      target_coords: Optional[Dict[str, np.ndarray]] = None) -> xr.DataArray:
        """
        Regrid an xarray DataArray and preserve metadata.
        
        Parameters
        ----------
        da : xr.DataArray
            Input data array with dimensions matching src_shape
        target_coords : dict, optional
            Target coordinates for output DataArray
            
        Returns
        -------
        xr.DataArray
            Regridded data with updated coordinates
        """
        # Extract grid dimensions (last N dims matching src_shape)
        grid_dims = da.dims[-len(self.src_shape):]
        batch_dims = da.dims[:-len(self.src_shape)]
        
        # Get data as numpy/jax array
        data = jnp.array(da.values)
        
        # Apply regridding
        if len(batch_dims) > 0:
            result = self.apply_batched(data, batch_dims=len(batch_dims))
        else:
            result = self(data)
        
        # Create output coordinates
        out_coords = {}
        
        # Keep batch coordinates
        for dim in batch_dims:
            out_coords[dim] = da.coords[dim]
        
        # Add target grid coordinates
        if target_coords is not None:
            out_coords.update(target_coords)
        elif self.weights.dst_grid_dims is not None:
            # Use stored dimension names if available
            for i, dim_name in enumerate(self.weights.dst_grid_dims):
                out_coords[dim_name] = np.arange(self.dst_shape[i])
        else:
            # Create generic dimension names
            for i, size in enumerate(self.dst_shape):
                dim_name = f"dim_{i}"
                out_coords[dim_name] = np.arange(size)
        
        # Determine output dimensions
        if self.weights.dst_grid_dims is not None:
            out_dims = batch_dims + self.weights.dst_grid_dims
        else:
            grid_dim_names = tuple(f"dim_{i}" for i in range(len(self.dst_shape)))
            out_dims = batch_dims + grid_dim_names
        
        # Create output DataArray
        result_da = xr.DataArray(
            np.array(result),
            dims=out_dims,
            coords=out_coords,
            attrs=da.attrs.copy()
        )
        
        # Add regridding metadata
        result_da.attrs['regrid_method'] = self.weights.method
        result_da.attrs['regrid_source_shape'] = str(self.src_shape)
        result_da.attrs['regrid_target_shape'] = str(self.dst_shape)
        
        return result_da
    
    def inverse(self) -> 'ESMFRegridder':
        """
        Create approximate inverse regridder (dst -> src).
        
        Note: This creates a new weight structure by swapping row/col indices.
        For true conservative remapping inverse, regenerate weights with ESMF.
        """
        inverse_weights = ESMFWeights(
            row_indices=self.weights.col_indices,
            col_indices=self.weights.row_indices,
            weights=self.weights.weights,
            src_shape=self.weights.dst_shape,
            dst_shape=self.weights.src_shape,
            src_mask=self.weights.dst_mask,
            dst_mask=self.weights.src_mask,
            method=f"inverse_{self.weights.method}",
            src_grid_dims=self.weights.dst_grid_dims,
            dst_grid_dims=self.weights.src_grid_dims
        )
        
        # Create new regridder with swapped weights
        inv_regridder = ESMFRegridder.__new__(ESMFRegridder)
        inv_regridder.weight_file = f"inverse_of_{self.weight_file}"
        inv_regridder.src_shape = self.dst_shape
        inv_regridder.dst_shape = self.src_shape
        inv_regridder.weights = inverse_weights
        inv_regridder._interp_fn = jit(inv_regridder._interpolate_impl)
        
        return inv_regridder
    
    def diagnostics(self) -> Dict[str, Any]:
        """Return diagnostic information about the regridder."""
        return {
            'method': self.weights.method,
            'src_shape': self.weights.src_shape,
            'dst_shape': self.weights.dst_shape,
            'src_size': self.weights.src_size,
            'dst_size': self.weights.dst_size,
            'n_weights': self.weights.n_weights,
            'sparsity': self.weights.n_weights / (self.weights.src_size * self.weights.dst_size),
            'avg_stencil_size': self.weights.n_weights / self.weights.dst_size,
            'has_src_mask': self.weights.src_mask is not None,
            'has_dst_mask': self.weights.dst_mask is not None,
        }


# ============================================================================
# Utility Functions
# ============================================================================

def create_regridder_pair(
    src_to_dst_file: str,
    dst_to_src_file: str,
    src_shape: Tuple[int, ...],
    dst_shape: Tuple[int, ...]
) -> Tuple[ESMFRegridder, ESMFRegridder]:
    """
    Create a pair of regridders for bidirectional interpolation.
    
    Parameters
    ----------
    src_to_dst_file : str
        Weight file for source to destination
    dst_to_src_file : str
        Weight file for destination to source
    src_shape : tuple
        Source grid shape
    dst_shape : tuple
        Destination grid shape
        
    Returns
    -------
    forward_regridder, backward_regridder
    """
    forward = ESMFRegridder(src_to_dst_file, src_shape, dst_shape)
    backward = ESMFRegridder(dst_to_src_file, dst_shape, src_shape)
    
    return forward, backward


def create_regridder_from_xarray(
    weight_file: str,
    src_da: xr.DataArray,
    dst_da: xr.DataArray
) -> ESMFRegridder:
    """
    Create regridder inferring shapes from xarray DataArrays.
    
    Parameters
    ----------
    weight_file : str
        Path to ESMF weight file
    src_da : xr.DataArray
        Example source data array
    dst_da : xr.DataArray
        Example destination data array
        
    Returns
    -------
    ESMFRegridder
    """
    src_shape = src_da.shape
    dst_shape = dst_da.shape
    
    return ESMFRegridder(weight_file, src_shape, dst_shape)


def verify_conservation(
    regridder: ESMFRegridder,
    src_data: jnp.ndarray,
    src_areas: Optional[jnp.ndarray] = None,
    dst_areas: Optional[jnp.ndarray] = None
) -> Dict[str, float]:
    """
    Verify conservation properties of regridding.
    
    Parameters
    ----------
    regridder : ESMFRegridder
        The regridder to test
    src_data : jnp.ndarray
        Test data on source grid
    src_areas : jnp.ndarray, optional
        Cell areas on source grid
    dst_areas : jnp.ndarray, optional
        Cell areas on destination grid
        
    Returns
    -------
    dict
        Conservation diagnostics
    """
    dst_data = regridder(src_data)
    
    # Calculate integrals
    if src_areas is not None:
        src_integral = jnp.sum(src_data * src_areas)
    else:
        src_integral = jnp.sum(src_data)
    
    if dst_areas is not None:
        dst_integral = jnp.sum(dst_data * dst_areas)
    else:
        dst_integral = jnp.sum(dst_data)
    
    # Calculate errors
    abs_error = dst_integral - src_integral
    if jnp.abs(src_integral) > 1e-10:
        rel_error = abs_error / src_integral
    else:
        rel_error = abs_error
    
    return {
        'src_integral': float(src_integral),
        'dst_integral': float(dst_integral),
        'absolute_error': float(abs_error),
        'relative_error': float(rel_error),
        'conserves': float(jnp.abs(rel_error)) < 1e-6
    }


# ============================================================================
# Example Usage
# ============================================================================

def example_usage():
    """Demonstrate usage of ESMFRegridder with xarray."""
    
    print("JAX-Friendly ESMF Regridder with xarray")
    print("=" * 60)
    
    # Example dimensions
    atm_shape = (180, 360)  # Atmosphere grid
    ocn_shape = (100, 200)  # Ocean grid
    
    print(f"\nSource grid shape: {atm_shape}")
    print(f"Target grid shape: {ocn_shape}")
    
    # Create sample xarray data
    lat_src = np.linspace(-90, 90, atm_shape[0])
    lon_src = np.linspace(0, 360, atm_shape[1])
    
    sample_data = xr.DataArray(
        np.random.randn(atm_shape[0], atm_shape[1]),
        dims=['lat', 'lon'],
        coords={'lat': lat_src, 'lon': lon_src},
        attrs={'units': 'K', 'long_name': 'Temperature'}
    )
    
    print(f"\nCreated sample xarray DataArray:")
    print(sample_data)
    
    # Usage examples (would work with actual weight file)
    print("\n" + "=" * 60)
    print("Usage patterns:")
    print("=" * 60)
    
    print("""
# 1. Basic regridding with JAX arrays:
regridder = ESMFRegridder('weights.nc', (180, 360), (100, 200))
output = regridder(input_data)

# 2. Regrid xarray DataArray (preserves metadata):
output_da = regridder.regrid_xarray(
    input_da,
    target_coords={'lat': target_lat, 'lon': target_lon}
)

# 3. Batched operations (e.g., time series):
timeseries_data = jnp.random.randn(365, 180, 360)  # (time, lat, lon)
output = regridder.apply_batched(timeseries_data, batch_dims=1)

# 4. Use in JAX compiled functions:
@jit
def process_and_regrid(data):
    processed = data * 2 + 1
    return regridder(processed)

# 5. Create from xarray DataArrays:
regridder = create_regridder_from_xarray(
    'weights.nc',
    src_da=input_dataarray,
    dst_da=target_dataarray
)
    """)
    
    print("\nKey features:")
    print("  ✓ Uses xarray for file I/O and metadata")
    print("  ✓ JIT-compiled for performance")
    print("  ✓ Works with JAX autodiff")
    print("  ✓ Preserves xarray metadata through regridding")
    print("  ✓ Supports batched operations")


if __name__ == "__main__":
    example_usage()
    
    print("\n" + "=" * 60)
    print("xarray integration benefits:")
    print("=" * 60)
    print("""
• Automatic dimension tracking
• Coordinate metadata preservation
• Natural integration with analysis workflows
• Easy inspection with .sel(), .isel()
• Seamless conversion to/from JAX arrays
    """)


# ============================================================================
# Advanced: Integration with Coordax
# ============================================================================

def create_coordax_regridder(
    weight_file: str,
    src_dims: Tuple[str, ...],
    dst_dims: Tuple[str, ...],
    src_coords: Dict[str, jnp.ndarray],
    dst_coords: Dict[str, jnp.ndarray]
):
    """
    Create a regridder that preserves coordax metadata.
    
    This bridges ESMFRegridder with the coordax-based coupler design.
    """
    import coordax as cx
    
    # Infer shapes from coordinates
    src_shape = tuple(len(src_coords[dim]) for dim in src_dims)
    dst_shape = tuple(len(dst_coords[dim]) for dim in dst_dims)
    
    # Create base regridder
    base_regridder = ESMFRegridder(weight_file, src_shape, dst_shape)
    
    def regrid_with_coords(var: cx.Variable) -> cx.Variable:
        """Regrid coordax variable while updating coordinates."""
        # Apply regridding to data
        new_data = base_regridder(var.data)
        
        # Create new variable with destination coordinates
        return cx.Variable(
            data=new_data,
            dims=dst_dims,
            coords=dst_coords,
            attrs=var.attrs
        )
    
    return regrid_with_coords
